name: Build Windows EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pycryptodome
      - run: pyinstaller --onefile --noconsole --name "18+videos" locker.py
      - uses: actions/upload-artifact@v4
        with:
          name: DMA_Locker
          path: dist/18+videos.exe
